### ISSUE TITLE
this repo is way too big

### ISSUE THREAD

**Issue by chharvey** [chharvey/chharvey.github.io#59]
Consider splitting repo up into separate components, each with their own function. Just some thoughts:
- [x] Javascript library ( #38 )
- [x] css codebase and style guide ( #32 )
- [ ] blog posts ( #36 , #53 , css-architecture, and one-off pages (coffee, rainbow, iexplore) )
- [ ] resume
- [ ] higher-ed and secondary-ed content ( #15 )

**Comment by chharvey** [comment]
UPDATE: leaving blog posts, resume, and higher- and secondary-ed content in this repo. will consider reopening if there is further need.
